// src/module-1/home/components/FrequentlyAsked.tsx
import React, { useState, useEffect, useRef } from 'react';
import '../styles/FrequentlyAsked.css';

const FrequentlyAsked: React.FC = () => {
  const [activeIndex, setActiveIndex] = useState<number | null>(0);
  const containerRef = useRef<HTMLDivElement>(null);

  const faqs = [
    {
      question: "What is billing software?",
      answer: "Billing software helps businesses generate invoices, track payments, manage customers, and automate GST compliance. It replaces manual bookkeeping with digital efficiency."
    },
    {
      question: "What is an invoice?",
      answer: "An invoice is a commercial document issued by a seller to a buyer, requesting payment for goods or services provided. It includes details like date, items, quantities, prices, taxes, and payment terms."
    },
    {
      question: "What is invoicing software?",
      answer: "Invoicing software automates the creation, sending, and tracking of invoices. It often integrates with accounting, inventory, and payment gateways for seamless business operations."
    },
    {
      question: "Which billing software is best for small businesses?",
      answer: "Anybill is ideal for small businesses — lightweight, affordable, feature-rich, and designed for ease of use. It handles GST, e-invoicing, inventory, and multi-device sync effortlessly."
    },
    {
      question: "What is the difference between an invoice and a bill?",
      answer: "Technically, they're similar — both request payment. But 'invoice' is more formal and used in B2B contexts, while 'bill' is common in retail or service industries. Legally, they may have different implications under GST."
    },
    {
      question: "What are the top features of a GST billing software?",
      answer: "Auto-GST calculation, e-Invoice & E-Way Bill generation, HSN/SAC code support, tax return filing assistance, digital signature integration, and real-time compliance alerts."
    },
    {
      question: "What is the difference between a tax invoice and an invoice?",
      answer: "A tax invoice includes mandatory GST details (GSTIN, HSN code, tax rates) and is required for claiming input tax credit. A regular invoice may not include these fields and is used for non-GST transactions."
    },
    {
      question: "What are the benefits of using a GST billing software?",
      answer: "Saves time, reduces errors, ensures legal compliance, auto-generates reports, integrates with banking/payment systems, and provides analytics for smarter business decisions."
    },
    {
      question: "What is the difference between an invoice and a receipt?",
      answer: "An invoice is generated to request payment, whereas receipts are provided as proof of payment. Invoices are generated before payment, and receipts upon receiving the payment."
    },
    {
      question: "What is a proforma invoice?",
      answer: "A proforma invoice outlines the estimated cost of the transaction and is generated to provide a rough estimate to the buyer. It's generated even before a sale is made and is not legally binding."
    },
    {
      question: "What is an invoice number?",
      answer: "An invoice number is a unique 16-digit alpha-numeric number assigned to each invoice generated by a seller. As per GST norms, the series needs to be changed for every financial year. A billing software generates a unique invoice number for every invoice based on the series you set."
    },
    {
      question: "What is the price of myBillBook billing software for PC?",
      answer: "myBillBook offers different plans to suit businesses of different sizes. Do check our <a href='/pricing' style='color:#8b4c3a; text-decoration:underline;'>Pricing Page</a> to know all the plans available."
    },
    {
      question: "Is myBillBook available on a monthly subscription?",
      answer: "We are currently offering plans on an annual subscription basis."
    },
    {
      question: "Can I have a free trial of myBillBook app?",
      answer: "Yes, if you haven't used your mobile number to register with the myBillBook billing app, you can enjoy a free trial."
    },
    {
      question: "Can I customise myBillBook subscription plans?",
      answer: "Yes, you can contact our customer service team to get tailor-made subscription plans based on your business needs."
    },
    {
      question: "What is e-invoicing software?",
      answer: "An <a href='#' style='color:#8b4c3a; text-decoration:underline;'>e-invoicing software</a> enables the creation of e-invoices quickly and easily in adherence to regulatory standards. It reduces the steps required to generate e-invoices and makes the e-invoice generation effortless. It integrates with accounting systems for seamless data flow, ensures accuracy, and provides secure transmission methods."
    },
    {
      question: "What is e-way billing software?",
      answer: "An <a href='#' style='color:#8b4c3a; text-decoration:underline;'>e-way billing software</a> enables the creation of e-way bills quickly and easily in adherence to regulatory standards. It facilitates the creation of e-way bills for the movement of goods, ensuring adherence to specified thresholds and legal requirements."
    },
    {
      question: "For which businesses or industries is billing software suitable?",
      answer: "Businesses from various industries can use billing software. Different types of billing software are available, including <a href='#' style='color:#8b4c3a; text-decoration:underline;'>restaurant billing software</a>, <a href='#' style='color:#8b4c3a; text-decoration:underline;'>medical billing software</a>, <a href='#' style='color:#8b4c3a; text-decoration:underline;'>hotel billing software</a>, and <a href='#' style='color:#8b4c3a; text-decoration:underline;'>retail shop billing software</a>."
    },
    {
      question: "Can I generate e-invoices and e-way bills together in myBillBook?",
      answer: "Yes, myBillBook supports single-click generation of e-invoices and e-way bills. While <a href='#' style='color:#8b4c3a; text-decoration:underline;'>e-invoicing</a>, you will find an option to generate e-way bills. You can use the same to initiate your <a href='#' style='color:#8b4c3a; text-decoration:underline;'>e-way billing</a> process."
    }
  ];

  // Animation on scroll
  useEffect(() => {
    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach(entry => {
          if (entry.isIntersecting) {
            entry.target.classList.add('visible');
          }
        });
      },
      { threshold: 0.1 }
    );

    const cards = containerRef.current?.querySelectorAll('.faq-question');
    cards?.forEach(card => observer.observe(card));

    return () => observer.disconnect();
  }, []);

  return (
    <section className="faq-section">
      <div className="faq-header">
        <h2>Frequently Asked Questions</h2>
        <p>Quick answers to all the questions you may have on Billing Software, GST invoicing, E-Invoicing, E-Way billing, and GST Billing Software.</p>
      </div>

      <div className="faq-layout" ref={containerRef}>
        <div className="faq-questions">
          {faqs.map((faq, index) => (
            <div
              key={index}
              className={`faq-question ${activeIndex === index ? 'active' : ''}`}
              onClick={() => setActiveIndex(index)}
            >
              <div className="question-number">{String(index + 1).padStart(2, '0')}</div>
              <div className="question-text">{faq.question}</div>
              <div className="question-indicator">
                <div className="plus-icon">+</div>
              </div>
            </div>
          ))}
        </div>

        <div className="faq-answers">
          <div className="answer-container">
            {faqs.map((faq, index) => (
              <div
                key={index}
                className={`answer-content ${activeIndex === index ? 'active' : ''}`}
                style={{ display: activeIndex === index ? 'block' : 'none' }}
              >
                <div dangerouslySetInnerHTML={{ __html: faq.answer }} />
              </div>
            ))}
          </div>
          
          <div className="dollar-animation">
            <div className="dollar-symbol">$</div>
            <div className="dollar-symbol">$</div>
            <div className="dollar-symbol">$</div>
            <div className="dollar-symbol">$</div>
            <div className="dollar-symbol">$</div>
            <div className="dollar-symbol">$</div>
            <div className="dollar-symbol">$</div>
            <div className="dollar-symbol">$</div>
            <div className="dollar-symbol">$</div>
            <div className="dollar-symbol">$</div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default FrequentlyAsked;